version: '3.7'

services:

  spark-master:
    build: ./master/
    container_name: master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 6066:6066
      - 7077:7077
      - 8080:8080  # spark-master WebUI  http://localhost:8080
    volumes:
      - ./spark/master/conf:/conf
      - ./spark/master/data:/tmp/data
      - 'myshare:/shared'

  spark-worker:
    build: ./worker/
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 6g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./spark/worker/conf:/conf
      - ./spark/worker/data:/tmp/data
      - 'myshare:/shared'


volumes:
  myshare:
    driver: local 
